### ISSUE TITLE
Error after running main.py

### ISSUE THREAD

**Issue by tobeginbegin** [brandonbondig/tgtg_auto#1]
Hi, thank you for this. I'm trying to implement this via my Macbook terminal. After running main.py, I get the following error:

Traceback (most recent call last):
  File "/Users/mike/projects/tgtg-auto-main/main.py", line 1, in <module>
    from tgtg_auto.functions import place_order_at_time
  File "/Users/mike/projects/tgtg-auto-main/tgtg_auto/functions.py", line 1, in <module>
    from tgtgpython.tgtg import TgtgClient
  File "/Users/mike/projects/tgtg-auto-main/tgtgpython/tgtg/__init__.py", line 10, in <module>
    from py_adyen_encrypt import encryptor
ModuleNotFoundError: No module named 'py_adyen_encrypt'

Could you let me know what I'm doing wrong? Thanks! Just learning python at the moment so not an expert.

**Comment by dibun75** [comment]
Install in this order.
pip3 install -r requirements.txt
pip3 install git+https://github.com/66niko99/py-adyen-encrypt.git
pip3 install requests cryptography pytz tgtg

**Comment by rregn** [comment]
after pip3 install -r requirements.txt
gtg_auto-main$ pip3 install git+https://github.com/66niko99/py-adyen-encrypt.git
Collecting git+https://github.com/66niko99/py-adyen-encrypt.git
  Cloning https://github.com/66niko99/py-adyen-encrypt.git to /tmp/pip-adl_c3_8-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-adl_c3_8-build/

**Comment by rregn** [comment]
still no solution for this stopper?
also .env/example  does not exist
